
modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
modId="thesideways"
version="${file.jarVersion}"
displayName="The Sideways"
logoFile="sidewayslogo.png"
#credits=""
authors="BonnieDev"

description='''
BonnieDev presents: The Sideways! A unique adventure in a new, strange land.
'''

[[dependencies.thesideways]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thesideways]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
